# tasks to complete before running roles
- hosts: localhost
  become: true
  pre_tasks:
    - name: pre-run | update package cache (debian,ubuntu)
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run role
- hosts: localhost
  tags: base
  become: true
  roles:
    - base
