# tasks to complete before running roles
- hosts: localhost
  become: true
  pre_tasks:
    - name: Updating indexes
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run role
- hosts: localhost
  name: Packages
  become: true
  roles:
    - base
